// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulahoiichsttthjsmtqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYWhvaWljaHN0dHRoanNtdHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDMxNDMsImV4cCI6MjA2ODU3OTE0M30.NNKXJH08g1VNxPHn6cfDHce5FV-uXmvzrZyB-hXgDeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});